<html>
<head>
<title>Asociaci&oacute;n Paraguaya de Amigos de la Rep&uacute;blica Popular China  (APACHI)</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<style type="text/css">
<!--
a:link {
	text-decoration:none;
	cursor:hand;
	color: #006699;
}
a:visited {
	text-decoration:none;
	color: #006699;
}
a:hover {
	color:#FF0000;
	cursor:hand;
}
-->
</style>
<style type="text/css">
<!--
.borde {
	border: 1px solid #999999;
}
body {
	background-color: #F8F8F8;
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 11px;
}
-->
</style>
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}

function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}
//-->
</script>
<link href="css/estilo.css" rel="stylesheet" type="text/css">
</head>

<body onLoad="MM_preloadImages('botones/home02.jpg','botones/noticias02.jpg','botones/contactenos02.jpg','botones/conozcanos02.jpg','images/cultura02.jpg','images/historia02.jpg','images/politica02.jpg','images/economia02.jpg','images/relaciones02.jpg')">
<table width="780" border="0" align="center" cellpadding="0" cellspacing="0" class="borde">
  <tr>
    <td><table width="100%"  border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><img src="images/muralla.jpg" width="585" height="177"></td>
        <td><img src="images/logo.jpg" width="195" height="177"></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td><table width="780"  border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="195" valign="top" background="images/fondo-noticias.jpg"><table width="100%"  border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td><a href="index.php" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Home','','botones/home02.jpg',1)"><img src="botones/home01.jpg" alt="Home" name="Home" width="195" height="21" border="0"></a></td>
          </tr>
          <tr>
            <td><a href="conozcanos.php" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Conozcanos','','botones/conozcanos02.jpg',1)"><img src="botones/conozcanos01.jpg" alt="Conozcanos" name="Conozcanos" width="195" height="18" border="0"></a></td>
          </tr>
          <tr>
            <td><a href="cultura.php" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Cultura','','images/cultura02.jpg',1)"><img src="images/cultura01.jpg" alt="Cultura" name="Cultura" width="195" height="18" border="0"></a></td>
          </tr>
          <tr>
            <td><a href="historia.php" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Historia','','images/historia02.jpg',1)"><img src="images/historia01.jpg" alt="Historia" name="Historia" width="195" height="18" border="0"></a></td>
          </tr>
          <tr>
            <td><a href="politica.php" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Politica','','images/politica02.jpg',1)"><img src="images/politica01.jpg" alt="Politica" name="Politica" width="195" height="18" border="0"></a></td>
          </tr>
          <tr>
            <td><a href="economia.php" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Econom&iacute;a','','images/economia02.jpg',1)"><img src="images/economia01.jpg" alt="Econom&iacute;a" name="Econom&iacute;a" width="195" height="18" border="0"></a></td>
          </tr>
          <tr>
            <td><a href="noticias.php" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Noticias','','botones/noticias02.jpg',1)"><img src="botones/noticias01.jpg" alt="Noticias" name="Noticias" width="195" height="18" border="0"></a></td>
          </tr>
          <tr>
            <td><a href="relaciones.php" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Relaciones con el Paraguay','','images/relaciones02.jpg',1)"><img src="images/relaciones01.jpg" alt="Relaciones con el Paraguay" name="Relaciones con el Paraguay" width="195" height="18" border="0"></a></td>
          </tr>
          <tr>
            <td><a href="contactenos.php" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Contactenos','','botones/contactenos02.jpg',1)"><img src="botones/contactenos01.jpg" alt="Contactenos" name="Contactenos" width="195" height="18" border="0"></a></td>
          </tr>
        </table>
        <table width="195" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td><img src="images/titulos-noticias.jpg" width="195" height="50"></td>
            </tr>
            <tr>
              <td><table width="100%" height="526"  border="0" cellpadding="2">
                <tr>
                  <td valign="top"><marquee id="threadticker" 
         direction=up 
         scrollAmount=2 
         style="border:0px solid #000000;padding:0px" 
         onMouseover="this.scrollAmount=0" 
         onMouseout="this.scrollAmount=2" width="100%" height="526" bgcolor="">
                    <p align=left>
                      <?
	   require("ver.php");
	   ?>
                        </marquee></td>
                </tr>
              </table></td>
            </tr>
          </table></td>
        <td width="585" valign="top"><table width="100%"  border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td height="111" valign="top" background="images/fondo-secciones.jpg"><img src="images/titulos/relaciones.jpg" width="228" height="57"></td>
          </tr>
          <tr>
            <td background="images/fondito-secciones.jpg"><table width="98%"  border="0" align="center" cellpadding="0" cellspacing="0">
              <tr>
                <td valign="top" class="texto"><table width="100%"  border="0" cellpadding="0" cellspacing="0" class="texto">
                  <tr>
                    <td><strong><img src="botones/flecha.gif" width="8" height="9"> <a href="#quinto">El quinto siglo paraguayo</a></strong></td>
                  </tr>
                  <tr>
                    <td><strong><img src="botones/flecha.gif" width="8" height="9"> <a href="#Paraguay">Paraguay &ndash; China</a></strong></td>
                  </tr>
                  <tr>
                    <td><strong><img src="botones/flecha.gif" width="8" height="9"> <a href="#taiwanesa">NO a la donaci&oacute;n taiwanesa</a></strong></td>
                  </tr>
                  <tr>
                    <td><strong><img src="botones/flecha.gif" width="8" height="9"> <a href="#chantaje">&iquest;D&oacute;nde est&aacute; el chantaje?</a></strong></td>
                  </tr>
                  <tr>
                    <td><strong><img src="botones/flecha.gif" width="8" height="9"> <a href="#migrantes">El Paraguay, Pa&iacute;s de migrantes</a></strong></td>
                  </tr>
                  <tr>
                    <td><strong><img src="botones/flecha.gif" width="8" height="9"> <a href="#babor">A babor, a estribor, hacia delante y hacia atr&aacute;s</a></strong></td>
                  </tr>
                  <tr>
                    <td><strong><img src="botones/flecha.gif" width="8" height="9"> <a href="#Gobierno">Gobierno no descarta establecer relaci&oacute;n con China Popular</a></strong></td>
                  </tr>
                  <tr>
                    <td><strong><img src="botones/flecha.gif" width="8" height="9"> <a href="#Duarte">Duarte Frutos no descarta en el futuro relacionamiento con Pek&iacute;n</a></strong></td>
                  </tr>
                  <tr>
                    <td><strong><img src="botones/flecha.gif" width="8" height="9"> <a href="#Consejo">XXVI Reuni&oacute;n del Consejo del Mercado Com&uacute;n</a></strong></td>
                  </tr>
                  <tr>
                    <td><strong><img src="botones/flecha.gif" width="8" height="9"> <a href="#Creydt">Oscar Creydt y la &ldquo;Presidencia de China&rdquo;</a></strong></td>
                  </tr>
                </table>                
                <p class="texto">&nbsp;</p>
                <p class="texto"><a name="quinto" id="quinto"></a></p>                <p><strong><strong><img src="botones/flecha.gif" width="8" height="9"></strong> E</strong><strong>l quinto siglo paraguayo </strong></p>
                  <p><strong>&iquest;SER&Aacute; ESTE SIGLO LA OPORTUNIDAD PARA QUE NUESTRO PA&Iacute;S ALCANCE A DESPEGAR HACIA LA PROSPERIDAD? </strong></p>
                  <p>El Paraguay, como territorio, fue descubierto por el portugu&eacute;s Aleixo Garc&iacute;a, aproximadamente en el a&ntilde;o 1522, mientras &eacute;ste usaba nuestro solar como plataforma de lanzamiento para una serie de actos de pillaje que se realizaron en los dominios del postrer imperio inca, hoy en d&iacute;a la hermana naci&oacute;n de Bolivia. Poco tiempo despu&eacute;s se fundaba el fuerte de Nuestra Se&ntilde;ora de la Asunci&oacute;n, y as&iacute; comenzaba para nosotros los paraguayos, el siglo XVI, un interminable calendario de abusos, explotaci&oacute;n humana y sufrimiento de nuestros antepasados ind&iacute;genas y criollos sometidos por el conquistador espa&ntilde;ol. El siglo XVII no hizo sino empeorar la situaci&oacute;n de nuestros tatarabuelos criollos e ind&iacute;genas, que fueron testigos del ataque de los bandeirantes, de los mamelucos, los excesos de la inquisici&oacute;n, las revoluciones comuneras y las batallas entre el gobierno y los jesuitas que se extendieron hasta el siglo XVIII. </p>
                  <p>El siglo XIX amaneci&oacute; con una temprana revoluci&oacute;n independiente, que trajo una brisa de esperanza y libertad a los corazones paraguayos, solo para terminar cayendo nuevamente en gobiernos autoritarios como los del Dr. Francia y la dinast&iacute;a L&oacute;pez, que desembocaron lamentablemente en la terrible guerra contra la Triple Alianza y la posterior dominaci&oacute;n extranjera. </p>
                  <p>El siglo XX recibi&oacute; con alegr&iacute;a a numerosos inmigrantes extranjeros que se unieron a nosotros en la tarea de construir una patria abierta y progresista; pero esa alegr&iacute;a fue acallada prontamente por una cadena de revoluciones internas y la sangrienta guerra del Chaco. Cuando logramos salir de guerras y revoluciones, quedamos nuevamente sumergidos en un autoritarismo -&iquest;el &uacute;ltimo?- que dur&oacute; medio siglo, y nos volvi&oacute; aun m&aacute;s cerrados y herm&eacute;ticos todav&iacute;a. </p>
                  <p>La llegada del siglo XXI a nuestra patria ocurri&oacute; poco despu&eacute;s de que nuestro pueblo comenzara a caminar el sendero de sus propias decisiones: Libertad de elegir, libertad de prosperar, libre comercio, y libertad para proyectar nuestro destino. Todo ello en momentos en que las dem&aacute;s naciones del mundo comenzaban a derribar los muros y las pesadas cortinas que los separaban. </p>
                  <p>&nbsp;</p>
                  <p><strong>Hoy </strong> vivimos en un mundo donde las murallas comienzan a convertirse en puentes, donde los antiguos cerrojos se tornan negocios, donde las ideas son mejores que las ideolog&iacute;as y donde los objetivos son apertura e integraci&oacute;n total. Ya no se trata de conquistar, sino de intercambiar. Comerciar resulta m&aacute;s lucrativo que saquear y liberar es mejor que trabar. </p>
                  <p>La cultura y el comercio se han vuelto m&aacute;s atractivos que las estrategias militares. La carrera armamentista se ha trocado por una r&aacute;pida marcha hacia el progreso y la integraci&oacute;n. Esta &uacute;ltima es mucho m&aacute;s justa y humana que la anterior, y de hecho, si la integraci&oacute;n es necesaria ... luego, el progreso del Paraguay es imperativo. </p>
                  <p>Nuestro pa&iacute;s necesita urgentemente de desarrollo y oportunidades reales de progreso, y la poblaci&oacute;n est&aacute; saliendo a las calles a reclamar cada vez con mayor &eacute;nfasis, pero nuestros timoneles pol&iacute;ticos dan la impresi&oacute;n de estar m&aacute;s preocupados por inconsistentes “lealtades” geopol&iacute;ticas que por la realidad actual de seis millones de paraguayos. Pareciera que nuestro pa&iacute;s es el &uacute;nico que a&uacute;n sigue girando en arcaicos esquemas ideol&oacute;gicos, de los cuales el contexto internacional se ha emancipado con todo &eacute;xito. </p>
                  <p>M&aacute;s all&aacute; de toda tendencia pol&iacute;tica internacional, el Paraguay requiere hoy de un reordenamiento urgente de las prioridades comerciales y productivas del pa&iacute;s. Antes que el discurso de un embajador for&aacute;neo - deber&iacute;a preocuparnos qu&eacute; produciremos y qu&eacute; venderemos el a&ntilde;o pr&oacute;ximo o “qu&eacute; pondremos en la mesa del pueblo a la hora de almorzar”. </p>
                  <p>Este es nuestro quinto siglo. Algo as&iacute; como un cumplea&ntilde;os muy especial para quienes hemos estado durante 500 a&ntilde;os sumergidos en la oscuridad y el encierro. </p>
                  <p>&iquest;Ser&aacute; &eacute;ste el siglo del despertar paraguayo? &iquest;Ser&aacute; que despertaremos al mundo abriendo nuestras puertas a un intercambio cultural y comercial, libre, con el resto de la humanidad? </p>
                  <p>Ya es hora de dejar de ser mendigos y asumir la heredad que la naturaleza generosamente nos ha dado. En vez de pedir donaciones para solucionar “el problema campesino” o “el problema de los sin techos”, usemos nuestro potencial campesino para producir y generar la riqueza latente de nuestra tierra. Nuestra tierra y nuestro pueblo, debidamente guiados, cuentan con los medios para marchar por el camino de la riqueza y la prosperidad. No somos un pa&iacute;s pobre, por m&aacute;s que pretendan hacernos creer tal cosa, no depende de Espa&ntilde;a ni de Norteam&eacute;rica, no depende de Pek&iacute;n ni de Taipei. Nuestro futuro depende s&oacute;lo de nosotros mismos. Seamos de una buena vez maduros como paraguayos y libres como humanos. </p>
                  <p>Elegir nuestro futuro, solo de nosotros depende, pero de todos nosotros. </p>
                  <p>&nbsp;</p>
                  <p><a href="#"><strong>arriba <img src="botones/flechaarriba.gif" width="9" height="8" border="0"></strong></a> </p>                  <p class="texto">&nbsp;</p>
                  <p class="texto"><a name="Paraguay" id="Paraguay"></a></p>
                  <p><strong><strong><img src="botones/flecha.gif" width="8" height="9"> </strong></strong><strong>Paraguay – China</strong></p>                  <strong>Una oportunidad inapreciable
                  </strong>                  <p><strong><em>LAS EXPECTATIVAS DE DOIS GRANDES NACIONES QUE SE COMPLEMENTAN DE MANERA SORPRENDENTE</em></strong></p>
                  <p><strong><em>C </em></strong><strong><em>hina ha sido hist&oacute;ricamente el pa&iacute;s m&aacute;s poblado de la humanidad y de hecho es considerada como una suerte de “continente aparte” por los analistas econ&oacute;micos y sociales de las principales potencias del mundo. Con sus 1.300 millones de habitantes y una insuficiencia cr&oacute;nica en materia de alimentos -e insumos para la elaboraci&oacute;n de los mismos-, tanto la China antigua como la gran Rep&uacute;blica Popular han estado siempre m&aacute;s all&aacute; de los c&aacute;lculos econ&oacute;micos de los expertos mundiales en la materia. Pero, en los &uacute;ltimos a&ntilde;os esta naci&oacute;n ha realizado cambios extraordinarios no solo en su rumbo pol&iacute;tico sino tambi&eacute;n en sus objetivos comerciales, abri&eacute;ndose al comercio internacional. </em></strong></p>
                  <p>“China comenz&oacute; a consumir y eso movi&oacute; el tablero econ&oacute;mico mundial”, afirma un art&iacute;culo publicado por la C&aacute;mara de Exportadores de la Rep&uacute;blica Argentina. Si bien lo que Carlos Tramutola en realidad afirma, es que “China comenz&oacute; a consumir <strong><em>productos extranjeros </em></strong>”, es totalmente cierto que “el tablero mundial se est&aacute; moviendo” de una manera tal que sin ser inesperada, ha causado sorpresa en los mercados burs&aacute;tiles y exportadores del mundo entero. Concretamente el <em>problema </em> chino de la escasez de alimentos, se ha convertido en una <em>soluci&oacute;n </em> econ&oacute;mica para numerosas naciones del mundo. Eso es lo que ha movido el tablero mundial. La pregunta es por qu&eacute;. </p>
                  <p>El gobierno chino ha declarado una nueva emergencia agropecuaria en el 2003 y ello significa sencillamente que lo que produce no alcanza para alimentar a sus 1.300 millones de habitantes. Y no se trata de una rara casualidad, siempre ha sido as&iacute;. Las cr&oacute;nicas chinas registran que, 2500 a&ntilde;os atr&aacute;s, el sabio Confucio fue convocado para solucionar los problemas agr&iacute;colas que afectaban a la </p>
                  <p>naci&oacute;n. Pero hoy en d&iacute;a los problemas son mayores y de alcance global, dado que la geograf&iacute;a china se ve afectada por un incontenible desierto, y que uno de cada cuatro habitantes del planeta es chino. </p>
                  <p>Debemos comprender que la naci&oacute;n que <em>necesita comprar comida </em> no es una naci&oacute;n sin recursos, y quiz&aacute;s baste mencionar que China tiene activadas 257 millones de l&iacute;neas telef&oacute;nicas celulares de &uacute;ltima generaci&oacute;n; para darnos una idea de que cuenta con recursos suficientes para <em>poder comprar. </em> M&aacute;s a&uacute;n si consideramos que el numero de aparatos celulares se quintuplic&oacute; en esta naci&oacute;n durante los diez primeros meses del 2003. De hecho, un pa&iacute;s que est&aacute; en condiciones de enviar naves tripuladas al espacio mientras que el poderoso Jap&oacute;n a&uacute;n no logra hacerlo con &eacute;xito, hace gala de recursos econ&oacute;micos y tecnol&oacute;gicos que lo colocan entre las primeras tres potencias mundiales de dicho orden. </p>
                  <p>La <em>necesidad china </em> de adquirir alimentos ha potenciado en forma inmediata las econom&iacute;as de una decena de naciones asi&aacute;ticas que han respondido a tiempo a la demanda china, y estas oportunas transacciones no solo han cambiado el horizonte econ&oacute;mico de otras naciones del mundo, sino que inclusive, han afectado a los surgentes bloques econ&oacute;micos mundiales, como por ejemplo, la Uni&oacute;n Europea, Estados Unidos y el Mercosur. </p>
                  <p><img src="images/fotos_nuevas/pag-04.gif" width="310" height="223" align="right">Dentro del bloque sudamericano, Argentina, Brasil y Uruguay han respondido con rapidez a esta oportunidad: Uruguay con lana, carne y trigo, y los dos “grandes” sudamericanos con un verdadero <em>aluvi&oacute;n </em> de exportaciones de soja. Pero pese a lograr exportaciones de 2.500 y 8.000 millones de d&oacute;lares, respectivamente, ni Buenos Aires ni Brasilia se han quedado all&iacute;. La ofensiva exportadora continu&oacute; con la presentaci&oacute;n de un extenso abanico de productos que, sin ser tan cuantitativos como la oleaginosa, cuentan en cambio con una mayor cotizaci&oacute;n internacional y conllevan mayor mano de obra, como las ofertas de l&aacute;cteos, aceites, frutas c&iacute;tricas y vinos. Todos estos sectores productivos que en el caso de Argentina- se encontraban en situaci&oacute;n cr&iacute;tica por la baja demanda internacional, han pasado de pronto a un nivel de producci&oacute;n que podr&iacute;a definirse con la frase <em>a toda m&aacute;quina. </em>No hay que creer que China compra baratos productos de baja calidad. Para acceder al mercado m&aacute;s grande del mundo, Argentina ha debido recurrir a estrictas negociaciones sobre par&aacute;metros de calidad y normas de seguridad sanitaria con Beijing, m&aacute;s a&uacute;n teniendo en el horizonte a los pulcros competidores del bloque europeo, Australia y Nueva Zelanda. Pero nuestros vecinos sudamericanos est&aacute;n venciendo en la pulseada y ello redunda en gigantescos ingresos econ&oacute;micos para sectores productivos que estaban hasta hace poco virtualmente paralizados. </p>                  
                  <p>Paraguay ha demostrado suficientemente que puede <em>aprobar </em> con excelentes calificaciones todos los ex&aacute;menes internacionales de calidad, por ejemplo con los productos c&aacute;rnicos que hemos exportado a Europa y al exigente mercado chileno. Adem&aacute;s, lo que China plantea, son normas de calidad de vigencia internacional, no los famosos “cupos” a los que nos han acostumbrado otros “clientes” pero que, en el fondo, solo buscaron durante a&ntilde;os manipular pol&iacute;ticamente nuestra necesidad de exportar. </p>
                  <p>Indudablemente se trata de una oportunidad inapreciable: China necesita comprar y Paraguay necesita vender. Lo que China quiere comprar es lo mismo que nosotros queremos vender. Y el volumen de la demanda es tan grande que, muy dif&iacute;cilmente Paraguay en sus mejores niveles de producci&oacute;n, pueda satisfacer totalmente. Tampoco se trata de una ocasi&oacute;n casual, o de una circunstancia pasajera, ya que la demanda de alimentos que China plantea tiene m&aacute;s de 2.500 a&ntilde;os de antig&uuml;edad e ir&aacute; creciendo en el futuro. </p>
                  <p>En pocas palabras, quienes siempre han predicado las promesas incumplidas hasta ahora de progreso, trabajo, prosperidad, desarrollo agr&iacute;cola y crecimiento econ&oacute;mico y tecnol&oacute;gico, ahora tienen la oportunidad de cumplir. </p>
                  <p>Indudablemente, dejar pasar esta ocasi&oacute;n de progreso y prosperidad ser&iacute;a una negligencia hist&oacute;rica grave. Seamos honestos y sinceros con nosotros mismos, no hay excusas, ni alianzas, ni donaciones, ni ideolog&iacute;as, ni <em>pol&iacute;ticas internacionales </em> que justifiquen tama&ntilde;a necedad ante la necesidad del pueblo paraguayo. Con la limosna nunca se ha logrado el desarrollo o la prosperidad en ninguna latitud de este planeta. </p>                  <p class="texto">&nbsp;</p>
                  <p class="texto"><a href="#"><strong>arriba <img src="botones/flechaarriba.gif" width="9" height="8" border="0"></strong></a></p>
                  <p class="texto">&nbsp;</p>                  <p class="texto"><a name="taiwanesa" id="taiwanesa"></a></p>
                  <p><strong><strong><img src="botones/flecha.gif" width="8" height="9"> </strong></strong><strong>NO a la donaci&oacute;n taiwanesa </strong><strong></strong></p>                  
                  <p align="right"><strong><em>Por Hugo L. Rubin G </em></strong>. </p>
                  <p>La prensa local ha publicado peri&oacute;dicamente art&iacute;culos que relatan la gran cantidad de donaciones realizadas por Taiw&aacute;n al Paraguay: equipos, ambulancias, puentes -que en alg&uacute;n caso no consigue usuarios debido al temor que genera la posibilidad de caer-y en mayor medida, dinero. Existen criterios b&aacute;sicos sobre las donaciones, no necesariamente dentro del &aacute;mbito jur&iacute;dico, sino en cuanto a sentido com&uacute;n, costumbre o moral. </p>
                  <p>Es com&uacute;n que un padre haga donaciones a sus hijos con el fin de facilitarle cierto bienestar que podr&iacute;a quedar m&aacute;s lejano si &eacute;stos tuvieran que valerse por s&iacute; mismos. Es costumbre que una instituci&oacute;n internacional o una naci&oacute;n ayude a otra cuando ocurre alguna cat&aacute;strofe, como la que recientemente nos afect&oacute; de manera tan dolorosa: se env&iacute;an medicamentos, alimentos, profesionales y hasta dinero para fines espec&iacute;ficos. Es normal la donaci&oacute;n a una instituci&oacute;n religiosa, a un ni&ntilde;o de la calle o una organizaci&oacute;n humanitaria e incluso cultural. </p>
                  <p>La donaci&oacute;n en el sentido jur&iacute;dico, seg&uacute;n nuestro C&oacute;digo Civil, art&iacute;culo 1.202 dice: ”Habr&aacute; donaci&oacute;n cuando una persona, por acto entre vivos, transfiere gratuitamente el dominio de una cosa o un derecho patrimonial, a favor de otra, que lo acepta”. </p>
                  <p>A contrario sensu, no es com&uacute;n entregar una cosa o bien a alguna persona o entidad sin relaci&oacute;n cercana sin esperar una contraprestaci&oacute;n. No es costumbre la donaci&oacute;n desproporcionada a un ente que no puede entregar alg&uacute;n tipo de servicio a cambio. No es normal realizar una donaci&oacute;n a los dirigentes de un Estado que no es capaz de administrar esos bienes de manera ordenada y se tiene la sospecha de que no ser&aacute;n utilizados para los fines previstos. </p>
                  <p>No es jur&iacute;dico seg&uacute;n nuestra legislaci&oacute;n recibir donaciones internacionales sin el estudio y la autorizaci&oacute;n del Congreso, aunque se le quiera dar el ropaje de legalidad realizando la transacci&oacute;n mediante fundaciones, principalmente cuando se sabe que &eacute;stas son manejadas por el c&iacute;rculo cercano al Presidente de la Rep&uacute;blica, que no ha consultado al Poder Legislativo. </p>
                  <p>Dar dinero a un drogadicto es acelerar su muerte, pensar que lo utilizar&aacute; para realizar un tratamiento en una instituci&oacute;n especializada es ingenuo, si se hace sin malicia. La ingenuidad en las relaciones internacionales no est&aacute; permitida porque puede costar vidas. La coyuntura del Paraguay es an&aacute;loga a la de ese drogadicto, aunque la intenci&oacute;n de la donaci&oacute;n sea hacer el bien. Taiw&aacute;n tiene que saber que el dinero no ser&aacute; utilizado con nobles prop&oacute;sitos. </p>
                  <p>Si la idea es lograr mantener cautivo el voto paraguayo en la ONU a favor de Taiw&aacute;n o impedir que el Paraguay establezca relaciones formales de cualquier tipo con China, es evidente que el m&eacute;todo es efectivo, pero los resultados son solamente negativos. Si Taiw&aacute;n tuviera la sana intenci&oacute;n de ayudar al desarrollo del Paraguay, lo podr&iacute;a hacer mediante controles estrictos de su donaci&oacute;n, realizando fiscalizaciones continuas sobre el destino del dinero, los pasos cumplidos, la calidad de los logros y las obras. No ”soltando” los fondos a discreci&oacute;n del gobernante de turno, para que &eacute;ste beneficie s&oacute;lo a sus allegados. </p>
                  <p>Si hubiera buena intenci&oacute;n, una donaci&oacute;n deber&iacute;a ir acompa&ntilde;ada de la milenaria sabidur&iacute;a china. Recordemos el refr&aacute;n que dice: ”Dale a un hombre un pez y comer&aacute; un d&iacute;a, ens&eacute;&ntilde;ale a pescar y comer&aacute; todos los d&iacute;as”. <em></em></p>
                  <p class="texto">&nbsp;</p>
                  <p class="texto"><a href="#"><strong>arriba <img src="botones/flechaarriba.gif" width="9" height="8" border="0"></strong></a></p>
                  <p class="texto">&nbsp;</p>                  <p class="texto"><a name="chantaje" id="chantaje"></a></p>
                  <p><strong><strong><img src="botones/flecha.gif" width="8" height="9"> </strong></strong><strong>&iquest;D&oacute;nde est&aacute; el chantaje? </strong></p>                  
                  <p align="right"><strong><em></em></strong></p>
                  <p><strong><em>QUERER COMERCIAR NO ES CHANTAJE EXIGIR FAVORES A CAMBIO DE DINERO S&Iacute; LO ES AUNQUE PODR&Iacute;A DARSELE UN NOMBRE A&Uacute;N PEOR </em></strong><strong></strong></p>
                  <p>Con exagerado malestar fue recibida la noticia de que el presidente argentino Nestor Kirschner aceptaba mediar ante su colega paraguayo para el restablecimiento del comercio entre nuestro pa&iacute;s y China. Exagerado malestar de una escasa minor&iacute;a de los paraguayos. Una minor&iacute;a que respondiendo a su billetera nuevamente hizo caso omiso a la conciencia colectiva del pa&iacute;s. La gesti&oacute;n reconciliatoria de Kirschner ya hab&iacute;a tenido un antecedente en otro intento similar del primer mandatario brasile&ntilde;o Da Silva, que tambi&eacute;n se pretendi&oacute; etiquetar como “intromisi&oacute;n en los asuntos internos del pa&iacute;s”. </p>
                  <p>Nada m&aacute;s rid&iacute;culo que semejante razonamiento: </p>
                  <p>1. Pretender formar parte de un bloque regional de pa&iacute;ses y al mismo tiempo considerar como intromisi&oacute;n una gesti&oacute;n oficiosa que intenta integrar al Paraguay a una alianza estrat&eacute;gica en la cual el resto del bloque ya se ha integrado; </p>
                  <p>2. Pretender definir como “asunto interno de un pa&iacute;s” su relacionamiento internacional. </p>
                  <p>Paraguay forma parte del Mercosur y pese a que todos los dem&aacute;s pa&iacute;ses obtienen extraordinarios beneficios econ&oacute;micos de su <em>sociedad estrat&eacute;gica </em> con China, contin&uacute;a siendo el &uacute;nico que renuncia a tales ventajas, en sacrificio de su propio desarrollo, a cambio de <em>donaciones y ayudas </em>de Taiw&aacute;n. </p>
                  <p>Podr&iacute;a decirse con cierta propiedad que las donaciones y pr&eacute;stamos obtenidos o solicitados de Taipei son amistosos, pero es necio afirmar que dichas “ayudas” son generosas. </p>
                  <p>&nbsp;</p>
                  <p><strong>Los “cuentos chinos” de Taipei</strong></p>
                  <p>Los <em>regalos </em>de Taipei encubren un gran perjuicio a nuestra econom&iacute;a, a nuestra sociedad y a nuestro desarrollo. Un perjuicio que se inicia desde el momento en que Taipei comercia abiertamente con Beijin, al mismo tiempo que nos exige a nosotros los paraguayos- no hacerlo. Y como corolario de dicha “lealtad”, terminamos comprando la producci&oacute;n china, previa intermediaci&oacute;n de Taiwan, con un sobrecosto para nuestros precios y un notorio r&eacute;dito a las arcas de los intermediarios taiwaneses. Lucro mediante, dejan de ser <em>tan generosas y amistosas </em> las donaciones y los prestamos de Taipei. </p>
                  <p>Paraguay est&aacute; renunciando a exportarle a China, pero, peor a&uacute;n, estamos despreciando las mutuas inversiones de capital y rechazando el gigantesco paso que ser&iacute;a incorporar tecnolog&iacute;a china a nuestra malherida agricultura y a nuestra rezagada industria. Paraguay est&aacute; renunciando a </p>
                  <p>cruzar la puerta hacia el futuro; estamos quedando atr&aacute;s. </p>
                  <p>Frente a realidades tan monumentales, se tornan rid&iacute;culos los argumentos “cortina de humo” como por ejemplo el famoso asunto del “voto paraguayo en la ONU”. &iquest;Qu&eacute; importancia tiene el voto paraguayo: un voto, cuando Beijin cuenta con el apoyo de 166 pa&iacute;ses contra solo 26 de Taipei? &iquest;Qu&eacute; importancia tiene un voto m&aacute;s o menos, cuando la Rep&uacute;blica Popular China es reconocida por la ONU y Taiw&aacute;n no? </p>
                  <p>La diferencia de propuestas y de actitudes es demasiado grande: China ofrece a Paraguay un trato comercial sincero, equitativo y duradero, en cambio Taiw&aacute;n nos est&aacute; chantajeando &iquest;o sobornando?- para obtener ganancias a costa del sufrimiento del pueblo paraguayo. Por nuestra parte, no hay mucha diferencia entre la actitud actual del gobierno asunceno y la despreciable conducta del votante que vende su c&eacute;dula de identidad por unos cuantos miles de guaran&iacute;es. </p>
                  <p>La diferencia contin&uacute;a creciendo cuando comprendemos que una sociedad estrat&eacute;gica con China popular (inversiones de capital + incorporaci&oacute;n de tecnolog&iacute;a + valor agregado a los productos agr&iacute;colas + mercado) nos permitir&iacute;a salir del estancamiento, convertirnos en productor-exportador, y lograr nuestro ansiado desarrollo. Se tratar&iacute;a de una alianza econ&oacute;mica, tecnol&oacute;gica y comercial con la naci&oacute;n que liderar&aacute; el mundo econ&oacute;mico del siglo XXI. </p>
                  <p>&nbsp;</p>                  <p><strong>Cinco mil a&ntilde;os de garant&iacute;a</strong></p>
                  <p>Hay quienes en su ceguera pretenden visualizar que la relaci&oacute;n con Taiw&aacute;n ser&aacute; duradera, en tanto que la relaci&oacute;n con China s&oacute;lo tienen visos de fugacidad. La relaci&oacute;n con Taiw&aacute;n durar&aacute;, con suerte, mientras esta isla contin&uacute;e existiendo como <em>gobierno aut&oacute;nomo </em>, y el propio mandatario de Taipei ha reconocido que siguen abiertas las posibilidades de una pronta reunificaci&oacute;n con la Rep&uacute;blica Popular. </p>
                  Por otro lado, s&oacute;lo 26 naciones siguen prestando su “lealtad” a Taipei, todas ellas subdesarrolladas, y algunas que no pasan de ser peque&ntilde;os islotes perdidos en el oc&eacute;ano. Ninguna de estas <em>naciones aliadas </em> est&aacute; en condiciones de asegurar la supervivencia de Taiw&aacute;n, que vive m&aacute;s bien de sus exportaciones a Estados Unidos y a la propia China. Los dos principales sustentadores econ&oacute;micos de Taiw&aacute;n no reconocen a la isla como Estado independiente: Washington pregona que “debe volver a integrarse al continente” y China, pacientemente, espera la reintegraci&oacute;n voluntaria de la provincia rebelde a su patria original. 
                  <p>Pese a una reciente publicaci&oacute;n local que hablaba de la “soberan&iacute;a” de Taiw&aacute;n, esta “naci&oacute;n” nunca se ha proclamado independiente de China, sino que, m&aacute;s all&aacute; de la rebeld&iacute;a original, siempre ha hablado de reunificaci&oacute;n. Como si esto fuera poco, el partido Kuomintang el mismo que huyendo vencido por el ejercito popular se autoexili&oacute; en Formosa en los a&ntilde;os 50, s&iacute;mbolo de la rebeli&oacute;n taiwanesa fue recientemente derrotado en las urnas por la propia oposici&oacute;n taiwanesa. </p>
                  <p>Todo esto es conocido tanto por Taiw&aacute;n como por Paraguay. Ambos gobiernos saben que al pueblo paraguayo le conviene mucho m&aacute;s el comercio con la creciente y pr&oacute;spera China que la <em>amistad extorsiva </em> que ofrece Taiw&aacute;n. Ese es el motivo por el cual Taipei permanentemente se encuentra predispuesta a hacer millonarios <em>pr&eacute;stamos </em>, o a efectuar <em>donaciones </em> con dudosa <em>finalidad social, </em>que en realidad <em></em>solo pretenden distraer y confundir la opini&oacute;n p&uacute;blica, cuando en realidad solo complacen a algunos sectores -nada distra&iacute;dos- de la clase pol&iacute;tica paraguaya. </p>
                  <p>&nbsp;</p>
                  <p><strong><img src="images/fotos_nuevas/pag-17.gif" width="330" height="217" align="left">Y... &iquest;d&oacute;nde est&aacute; el chantaje? </strong></p>
                  <p>As&iacute; y todo, un pu&ntilde;ado de neo-ide&oacute;logos de la soberan&iacute;a paraguaya alzan sus voces de protesta y publican costosas p&aacute;ginas de prensa reclamando <em>intromisi&oacute;n, injerencia, intereses pol&iacute;ticos e indignante chantaje </em>, cuando en realidad otro chantaje pre-existente es el que inclusive paga los costos de publicaci&oacute;n . </p>
                  <p>Se habla de chantaje cuando el gobierno de Beijin recurre a pa&iacute;ses amigos para reanudar una amistad conveniente a ambas partes, pero nadie parece reconocer intenciones extorsivas en el grave hecho de manipular nuestro comercio exterior para beneficio de Taiw&aacute;n. Si el gobierno chino debe recurrir a la intermediaci&oacute;n de los presidentes de Argentina y Brasil, es simplemente porque Paraguay no permite el desembarco de ning&uacute;n “chino rojo” en Asunci&oacute;n, trato irrespetuoso que incluye desde los m&aacute;s simples agricultores hasta el propio presidente Hu-Jintao. En cambio, los paraguayos que llegan a China son tratados con todo respeto y consideraci&oacute;n como </p>
                  <p>cualquier otro honorable extranjero. </p>
                  <p>Para colmo de males, aun cuando tras recibir semejante humillaci&oacute;n muy poco coherente con nuestra Constituci&oacute;n y nuestra <em>tradici&oacute;n cristiana </em>- intentan hacernos llegar sus mensajes conciliatorios, no a trav&eacute;s de un embajador sino por intermedio de dos presidentes amigos nuestros, hay quienes pretenden ver en dicha actitud un indignante chantaje. </p>
                  <p>Querer relacionarse con una naci&oacute;n amistosa no es chantaje. Chantaje es exigir favores a cambio de dinero, aunque tambi&eacute;n podr&iacute;a d&aacute;rsele nombres mucho peores: soborno, prostituci&oacute;n, etc. Taiw&aacute;n dice que romper&aacute; relaciones con Paraguay si el gobierno de Asunci&oacute;n abre una oficina comercial china en nuestro pa&iacute;s. &iquest;Y por qu&eacute; el gobierno de Taipei no aplica la misma regla con su propio comercio y deja de comprar de China continental? Eso, m&aacute;s que chantaje, parece una burla. </p>
                  <p>China existe como naci&oacute;n hace m&aacute;s de 5.000 a&ntilde;os. Ya exist&iacute;a mucho antes de que los espa&ntilde;oles descubrieran Am&eacute;rica, antes de que Paraguay naciera, y antes de que el Kuomintang se fugara a la isla de Formosa. Y seguir&aacute; existiendo. </p>
                  <p>Lo que deber&iacute;amos preguntarnos es: </p>
                  <p>&middot; &iquest;Qu&eacute; haremos nosotros cuando la provincia rebelde se reconcilie con su pa&iacute;s natural y ya no nos necesiten m&aacute;s? </p>
                  <p>&middot; &iquest;Qu&eacute; haremos cuando los taiwaneses nos digan que ya no podemos recibir “donaciones” como tampoco comerciar con la gran naci&oacute;n china? </p>
                  <p>&middot; &iquest;C&oacute;mo explicaremos tama&ntilde;a torpeza a nuestros hijos dentro de diez o veinte a&ntilde;os? </p>
                  <p>&iquest;Entender&aacute;n que hubo gobernantes tan ciegos o solo interesados en su provecho personal? </p>                  <p class="texto">&nbsp;</p>
                  <p class="texto"><a href="#"><strong>arriba <img src="botones/flechaarriba.gif" width="9" height="8" border="0"></strong></a></p>                  <p class="texto">&nbsp;</p>
                  <p class="texto"><a name="migrantes" id="migrantes"></a></p>
                  <p><strong><strong><img src="images/fotos_nuevas/pag-21.gif" width="290" height="163" align="right"><img src="botones/flecha.gif" width="8" height="9"> </strong></strong><strong>El Paraguay, Pa&iacute;s de migrantes </strong>                  </p>                  
                  <p><em></em></p>
                  <p>A lo largo de su historia, la Rep&uacute;blica del Paraguay ha pasado por varios cap&iacute;tulos en los que las migraciones y los migrantes han desempe&ntilde;ado un rol protag&oacute;nico. Nuestra historia est&aacute; enriquecida de referencias hacia inmigrantes que llegados a nuestra tierra la han adoptado como suya, ya sea defendi&eacute;ndola en los momentos dif&iacute;ciles, o contribuyendo con su sabidur&iacute;a y su cultura al desarrollo del pa&iacute;s. </p>
                  <p>Si bien el pa&iacute;s tuvo restricciones para el ingreso de poblaci&oacute;n extranjera durante casi todo el per&iacute;odo de mandato del Dr. Francia (1814-1840), ni bien &eacute;ste fue sucedido en el cargo, se dio una lenta apertura para el ingreso de extranjeros, pero fuera de una pol&iacute;tica orientada desde el Estado, que se dar&iacute;a m&aacute;s tarde. Carlos Antonio L&oacute;pez, quien sucede a Francia, asume una pol&iacute;tica mas abierta. Producto de esta reorientaci&oacute;n de la pol&iacute;tica inmigratoria fue la organizaci&oacute;n de un programa de colonizaci&oacute;n europea sobre la base de colonos franceses, que constituy&oacute; el primer contingente que en tal car&aacute;cter ingresa al Paraguay en 1855. Posterior a este acontecimiento y luego de la finalizaci&oacute;n de la Guerra de la Triple Alianza, los sucesivos gobiernos habidos en el Paraguay promocionaron oficialmente la inmigraci&oacute;n, por lo que en fecha 7 de junio de 1881 fue promulgada la primera Ley de Inmigraci&oacute;n y Colonizaci&oacute;n. El Estado paraguayo concedi&oacute; a los inmigrantes, en virtud de aquella Ley, considerables beneficios. </p>
                  <p>La primera Constituci&oacute;n, que data de 1844, prohib&iacute;a en su Art. 10 (titulo X) el tr&aacute;fico de esclavos o de negros, aun con el t&iacute;tulo o pretexto de colonos. En el texto constitucional de 1870 se dispon&iacute;a: ”El gobierno fomentar&aacute; la inmigraci&oacute;n americana y europea y no podr&aacute; restringir, limitar ni gravar con impuesto alguno la entrada en el territorio paraguayo de los extranjeros que traigan por objeto mejorar las industrias, labrar la tierra e introducir y ense&ntilde;ar las ciencias y las artes”, (Art. 6&ordf;). Asimismo expresaba en el Cap&iacute;tulo referido a los Derechos y Garant&iacute;as que en “la Rep&uacute;blica del Paraguay no hay esclavos; si alguno existiere, queda libre desde la jura de esta Constituci&oacute;n. Los esclavos que de cualquier modo se introduzcan, quedan libres por el solo hecho de pisar territorio paraguayo” (Art.25) y que los extranjeros gozan en todo el territorio de la Naci&oacute;n de todos los derechos civiles del ciudadano; pueden ejercer sus </p>
                  <p>industrias, comercios y profesi&oacute;n; poseer bienes ra&iacute;ces, comprarlos y enajenarlos; navegar los r&iacute;os; ejercer libremente su culto; testar y casarse conforme a las leyes. No est&aacute;n obligados a admitir la ciudadan&iacute;a ni a pagar contribuciones forzosas extraordinarias” (Art. 33). </p>
                  <p>La Carta Magna de 1940 contiene disposiciones similares en sus Declaraciones Generales: “El Gobierno fomentar&aacute; la inmigraci&oacute;n americana y europea y reglamentar&aacute; la entrada de los extranjeros al pa&iacute;s. (Art.91). Los extranjeros gozan dentro del territorio de la Rep&uacute;blica de los derechos civiles del ciudadano, de acuerdo con las leyes reglamentarias de su ejercicio; pueden ejercer su industria, comercio o profesi&oacute;n, poseer bienes ra&iacute;ces, testar y casarse. Si atentaren contra la seguridad de la Rep&uacute;blica o alteraren el orden p&uacute;blico, el Gobierno podr&aacute; disponer su expulsi&oacute;n del pa&iacute;s, de conformidad con las leyes reglamentarias. Los extranjeros no est&aacute;n obligados a admitir la ciudadan&iacute;a (Art.36). </p>
                  <p>Por su parte, el Pre&aacute;mbulo del texto de 1967 expresa el deber de consagrar los Derechos Humanos, y luego de asegurar la libertad, la igualdad, la justicia y el orden, la paz interior, la defensa nacional, el desarrollo econ&oacute;mico y el progreso social y cultural, garantiza la dignidad y el bienestar de las generaciones de paraguayos y de todos los hombres del mundo que lleguen a compartir con ellos el esfuerzo de labrar un destino superior en el concierto de las naciones libres. En el Art. 52 dispone que los extranjeros podr&aacute;n avecindarse en el Paraguay con las formalidades y requisitos establecidos por la ley. El Art. 130 expresa que se fomentaran la repatriaci&oacute;n de los paraguayos y la migraci&oacute;n interna atendiendo a razones demogr&aacute;ficas, econ&oacute;micas o sociales, preferentemente bajo el sistema de colonias con cooperaci&oacute;n oficial, as&iacute; como la inmigraci&oacute;n de extranjeros &uacute;tiles al desarrollo general del pa&iacute;s, con sujeci&oacute;n a las leyes reglamentarias. </p>
                  La Constituci&oacute;n Nacional de 1992, vigente, en su Art. 41, sobre el derecho al tr&aacute;nsito o libertad de circulaci&oacute;n de las personas, hace una distinci&oacute;n en cuanto a los sujetos de este derecho: atribuye a todos lo paraguayos el derecho a residir en su patria, y a los habitantes el derecho de transitar libremente por el territorio nacional, distinguiendo entre: a) los extranjeros sin radicaci&oacute;n definitiva, cuyos derechos al tr&aacute;nsito en el territorio nacional ser&aacute;n reglamentados por la Ley de
Migraciones, con observancia de los derechos comprendidos en el derecho de tr&aacute;nsito y los convenios internacionales; y b) los extranjeros con radicaci&oacute;n definitiva.
<p>La Ley n&ordm; 978 regula la migraci&oacute;n de extranjeros; el Art. 141 dispone que el &oacute;rgano de ejecuci&oacute;n de la pol&iacute;tica migratoria nacional ser&aacute; la Direcci&oacute;n General de Migraciones, dependiente del Ministerio del Interior. En t&eacute;rminos generales, la Pol&iacute;tica Migratoria del Paraguay, entre otros, tiene como objetivos: a) Atraer inmigrantes con capital para la instalaci&oacute;n de medianas y peque&ntilde;as empresas agroindustriales u otras actividades de inter&eacute;s para el pa&iacute;s; b) Incorporar selectivamente recursos humanos calificados deficitarios en el pa&iacute;s para acompa&ntilde;ar el proceso de desarrollo industrial, t&eacute;cnico, cient&iacute;fico que planifican los organismos competentes. </p>
                  <p>Para el cumplimiento de estos objetivos de pol&iacute;tica migratoria, la Ley de referencia posibilita el ingreso de extranjeros en la categor&iacute;a de “Residentes Permanentes”, que incluye: a) los inmigrantes, los cuales podr&aacute;n ser espont&aacute;neos, asistidos y con capital; b) los inversores; c) los jubilados, pensionados o rentistas; d) los parientes extranjeros de ciudadanos paraguayos; los “residentes temporarios”, que incluyen a cient&iacute;ficos, empresarios, estudiantes, periodistas, artistas, deportistas, becarios, personas que pertenecen a organizaciones internacionales reconocidas por el gobierno, para realizar actividades ben&eacute;ficas o asistenciales, religiosos, asilados pol&iacute;ticos, refugiados. </p>
                  <p>La categor&iacute;a no residentes comprende: turistas, integrantes de espect&aacute;culos p&uacute;blicos, tripulantes de medios de transporte internacionales, pasajeros en tr&aacute;nsito, trabajadores migrantes fronterizos, tr&aacute;nsito vecinal fronterizo, inversores, periodistas y dem&aacute;s profesionales de medios de comunicaci&oacute;n acreditados para eventos especiales. Los &uacute;nicos impedimentos por los cuales el Paraguay se reserva el derecho de permitir el ingreso de inmigrantes est&aacute;n establecidos en el Art. 6&ordm; inc. 1/8 de la Ley 978 que entre otros podemos citar el estar afectado de enfermedad infecto contagiosa transmisible, padecer enfermedad o insuficiencia mental, los enfermos cr&oacute;nicos o que tengan disminuci&oacute;n por defectos f&iacute;sicos o ps&iacute;quicos que le imposibilite el ejercicio de profesi&oacute;n, oficio, industria, o arte que </p>
                  <p>posean, los que fueran condenados por delitos dolosos a mas de dos a&ntilde;os de penitenciar&iacute;a, los que tengan antecedentes penales, excepto que no denoten peligrosidad, los que ejercen o lucran con la prostituci&oacute;n, los que carecen de profesi&oacute;n, oficio, industria u otro medio de vida l&iacute;cito, los que trafican con personas o sus &oacute;rganos y tr&aacute;fico de drogas, los expulsados que tengan prohibido el ingreso o reingreso en la Rep&uacute;blica. </p>
                  <p>En definitiva, el Paraguay abre sus brazos a todos los inmigrantes del mundo que quieran ingresar ya sea como visitantes o con intenci&oacute;n de permanecer en ella, toda vez que tenga como fin el de coadyuvar al desarrollo nacional, no haciendo distinci&oacute;n de nacionalidad, raza, religi&oacute;n e ideolog&iacute;a pol&iacute;tica. </p>
                  <p>El Paraguay puede considerarse entonces un pa&iacute;s hist&oacute;ricamente de migrantes, por haber comprendido desde el d&iacute;a mismo de su independencia, la importancia de abrirse al mundo y recibir a todos los extranjeros que quieran juntos con los nacionales, labrar la grandeza del pa&iacute;s. Esto se desprende de las sucesivas constituciones y legislaciones que rigieron la vida institucional del pa&iacute;s; por ello no existe ning&uacute;n impedimento legal para no recibir a cualquier extranjero que no sean los taxativamente enunciados en la ley de migraciones. Por tanto, el rechazo o restricci&oacute;n de ingresos extranjeros como los que se est&aacute;n dando y que afectan a los de nacionalidad chino continental, se funda &uacute;nica y exclusivamente en decisiones personales del responsable del Ejecutivo, que nada tiene que ver con la legislaci&oacute;n vigente. </p>
                  <p align="right"><strong><em>Dr. Gustavo Franco <br>
                  </em></strong><strong><em>Ex Director General de Migraciones </em></strong></p>
                  <p class="texto">&nbsp;</p>
                  <p class="texto"><a href="#"><strong>arriba <img src="botones/flechaarriba.gif" width="9" height="8" border="0"></strong></a></p>                  <p class="texto">&nbsp;</p>                  
                  <p class="texto"><a name="babor" id="babor"></a></p>
                  <p><strong><strong><img src="botones/flecha.gif" width="8" height="9"> </strong></strong><strong>A babor, a estribor, hacia delante y hacia atr&aacute;s</strong></p>                  
                  <p>&nbsp;</p>                  <p><strong><em>&iquest;NADIE SE HA PREGUNTADO, REALMENTE, HACIA D&Oacute;NDE VAMOS?</em></strong></p>
                  <p><em>Muchas veces la realidad se nos presenta totalmente confusa, y el embrollo es de tal magnitud que tendemos a dudar de nuestra propia cordura. Hace miles de a&ntilde;os que la humanidad se pregunta qu&eacute; es la realidad. Sobre este particular, se le atribuye al gran sabio y fil&oacute;sofo de la India, Siddhartha Gautama, el siguiente an&aacute;lisis de la realidad. Esta“consiste en la apariencia, la naturaleza, la entidad, la fuerza, la influencia, la causa interna, la causa externa o relaci&oacute;n, el efecto latente, el efecto manifiesto y su coherencia del principio al fin”. </em></p>
                  <p><strong>Nuestra realidad </strong></p>
                  <p><strong></strong></p>
                  <p><strong>La apariencia </strong></p>
                  <p>Un claro ejemplo de confusi&oacute;n lo tenemos en Paraguay con relaci&oacute;n a la pol&iacute;tica internacional de nuestro gobierno. El propio presidente que el pasado mayo regres&oacute; de China, inform&oacute; en una conferencia de prensa que “Paraguay <em>no descarta </em> establecer relaciones con China Popular ”(1). Pese a esta “clara y contundente afirmaci&oacute;n”, en el mismo art&iacute;culo se puede leer: “Las declaraciones del mandatario se contraponen a las del vicepresidente, Luis Castiglioni, quien hab&iacute;a cerrado puertas incluso al posible relacionamiento comercial” con la Republica de China. Ante esta situaci&oacute;n, y otras anteriores, el gobierno paraguayo contin&uacute;a brindando una apariencia de desorden e improvisaci&oacute;n, un panorama documentado, de que sus hombres no se han puesto de acuerdo sobre pol&iacute;tica exterior y que cada quien opina y decide a su antojo. </p>
                  <p>&nbsp;</p>
                  <p><strong>La naturaleza </strong></p>
                  <p>Sobre el mismo tema, y a ra&iacute;z de la misma conferencia de prensa, otro matutino capitalino destac&oacute;:“El presidente anunci&oacute; una pol&iacute;tica exterior para captar inversiones”.(2) Agregando, adem&aacute;s, que “en adelante el Paraguay establecer&aacute; una pol&iacute;tica econ&oacute;mica agresiva sin limitarse a 'simples cooperaciones', sino m&aacute;s bien apuntando a captar inversiones extranjeras que posibiliten el desarrollo econ&oacute;mico y social del pa&iacute;s. 'Queremos reorientar las relaciones del Paraguay con el mundo'.” Pero, pese a todo lo afirmado, el propio Presidente “inform&oacute; sobre un pr&eacute;stamo de treinta millones de d&oacute;lares a quince a&ntilde;os de plazo y un bajo inter&eacute;s”, con lo cual pareciera que antes que captar inversiones <em>en forma agresiva </em>, seguimos mendigando “simples cooperaciones” que, a ojos de los cr&iacute;ticos del gobierno, contin&uacute;an siendo apoyo econ&oacute;mico de &iacute;ndole pol&iacute;tica. Adem&aacute;s inform&oacute; sobre una donaci&oacute;n de 29 millones de d&oacute;lares para la construcci&oacute;n de viviendas populares. De esta forma, percibimos a la pol&iacute;tica exterior paraguaya como de naturaleza falsa y simulada. </p>
                  <p>&nbsp;</p>                  <strong>La entidad</strong>                  <p>La impresi&oacute;n que caus&oacute; el discurso presidencial, visto en el marco de los logros concretos u obtenidos tras una costosa gira de dos semanas alrededor del planeta, fue de que “Nicanor regres&oacute; con las maletas cargadas solo de promesas”(3). S&iacute; tenemos en cuenta que posiblemente obtuvo treinta de los 125 millones de d&oacute;lares que fue a pedir <em>prestados </em>a Taiw&aacute;n, y que su discurso fue netamente futurista: “V <em>amos a </em> terminar con la pol&iacute;tica exterior simb&oacute;lica”, “La pol&iacute;tica exterior <em>ser&aacute; </em>agresiva”, etc., parecer&iacute;a que, inclusive, hasta las promesas que trajo el gobernante de nuestro pa&iacute;s son &uacute;nicamente las suyas propias. Nuestro gobierno, nuestro Poder Ejecutivo, como instituci&oacute;n pol&iacute;tica democr&aacute;tica, antes que ejecutar la voluntad popular, da la impresi&oacute;n de hacer exactamente lo contrario, ocult&aacute;ndose tras interminables “discursos de deseos”. </p>
                  <p>&nbsp;</p>                  <strong>La fuerza y la influencia</strong>
                  <p>Con respecto al relacionamiento con la mayor naci&oacute;n de Asia, el Presidente de la Rep&uacute;blica, quien afirm&oacute; estar “en un mundo global”, parece no haberse enterado de que el Mercosur <em>como bloque </em> ya ha realizado, en Beijing, el Quinto Di&aacute;logo Mercosur-Rep&uacute;blica Popular China, ocasi&oacute;n en que se conform&oacute; el grupo de enlace entre ambas partes y se acord&oacute; iniciar un estudio de factibilidad sobre un eventual acuerdo comercial. Pese a <em>no estar enterado </em>, el Presidente paraguayo dej&oacute; su firma en dicho documento(4), al lado de las firmas de Kirchner, Lula da Silva y Batlle Iba&ntilde;ez. &iquest;Qu&eacute; fuerz <strong>a </strong> moral puede tener un Estado, cuyo propio gobierno dice p&uacute;blicamente lo contrario a lo que firma y escribe? &iquest;Qu&eacute; fuerz <strong>a </strong> pol&iacute;tica y jur&iacute;dica tiene un gobierno, que sacrifica deliberadamente el camino del bienestar de su pueblo, la senda del progreso comercial del Paraguay, a favor de influencias pol&iacute;ticas y econ&oacute;micas ajenas al pueblo paraguayo? </p>
                  <p>&nbsp;</p>                  <p><strong>La causa interna y la causa externa</strong></p>
                  <p>No debe extra&ntilde;arnos a todos los paraguayos que el Ejecutivo nacional afirme, en forma p&uacute;blica y rampante, que “acabar&aacute; con la corrupci&oacute;n interna del pa&iacute;s”, que “pondr&aacute; fin al atraso, la pobreza y el sufrimiento paraguayo”, pero que a la hora de la verdad, cuando se esperan decisiones efectivas para el bien -presente y futuro- de la rep&uacute;blica, se opte, arbitraria e inexcusablemente, por seguir “pidiendo fiado”, antes que por hacer tratos y emprendimientos comerciales que den oportunidad a la fuerza productiva del pa&iacute;s de “salir adelante” y sacar adelante a toda la naci&oacute;n. Parece como si existieran causas externas, m&aacute;s importantes, m&aacute;s poderosas -o m&aacute;s atractivas- que la voluntad del pueblo paraguayo, &uacute;nica causa, por la cual debe luchar nuestro gobierno. </p>                  
                  <p>&nbsp;</p>
                  <p><strong>Efecto latente y efecto manifiesto </strong></p>
                  <p>Existe en el pa&iacute;s una latente pero creciente tensi&oacute;n social que es originada por antiguos abusos p&uacute;blicos contra el pueblo paraguayo. El pa&iacute;s arrastra desde hace generaciones un creciente descontento, desprecio y animosidad contra los &uacute;ltimos gobiernos. Esa frustraci&oacute;n comienza a manifestarse como un abierto, y cada vez m&aacute;s violento, enfrentamiento a todo lo que significa Estado: las leyes, la propiedad, la vida, la paz. Mientras tanto el gobierno, antes que encarar de una vez por todas un pa&iacute;s productivo, un r&aacute;pido crecimiento de la producci&oacute;n, las exportaciones y los recursos, pone en jaque a lo que a&uacute;n queda de - la fuerza productiva, contin&uacute;a endeudando al pa&iacute;s, y cierra las puertas a los grandes clientes de nuestro pa&iacute;s. </p>
                  <p>&nbsp;</p>
                  <p><strong><img src="images/fotos_nuevas/pag-23.gif" width="230" height="125" align="left">Coherencia del principio al fin </strong></p>
                  <p>Todo lo mencionado anteriormente pone de resalto la absoluta falta de coherencia en el accionar gubernamental, que simula llevar una pol&iacute;tica pendular entre “las dos Chinas”, cuando en realidad hay una sola China y lo &uacute;nico que se est&aacute; haciendo es obtener <em>donaciones </em> a cambio de perjudicar, quiz&aacute;s para siempre, el futuro productivo y comercial de todos los paraguayos. </p>
                  <p>No hay coherencia para evitar otros calificativos, en un gobierno que dice “combatir la corrupci&oacute;n” y <em>pr&eacute;stamos mediante, </em> prefiere beneficiar a los intermediarios taiwaneses, en contra de los intereses de los productores paraguayos. </p>
                  <p>1. La Naci&oacute;n, 31/05/2004 </p>
                  <p>2. Noticias, 31/05/2004 </p>
                  <p>3. &Uacute;ltima Hora, 31/05/2004 </p>
                  <p>4. Comunicado conjunto de los Presidentes de los Estados Partes del Mercosur, 08/07/2004 </p>
                  <p>5. Lotus Sutra.
</p>
                  <p>&nbsp;</p>
                  <p><a href="#"><strong>arriba <img src="botones/flechaarriba.gif" width="9" height="8" border="0"></strong></a></p>                  <p>&nbsp;</p>
                  <p class="texto"><a name="Gobierno" id="Gobierno"></a></p>
                  <p><strong><strong><img src="botones/flecha.gif" width="8" height="9"> </strong></strong><strong>Gobierno no descarta establecer relaci&oacute;n con China Popular </strong>                  </p>                  
                  <p align="right">Diario La Naci&oacute;n - Paraguay . </p>
                  <p>Paraguay ”no descarta” establecer relaciones con China Popular, admiti&oacute; ayer Nicanor Duarte Frutos. El Presidente de la Rep&uacute;blica destac&oacute; que para que ello se d&eacute; ”en un futuro”, su gobierno exigir&aacute; ”solamente respeto, decencia y veracidad”. Las declaraciones refutan a las vertidas por el vicepresidente Luis Castiglioni, quien tras la sospecha lanzada desde Beijing sobre el supuesto apoyo taiwan&eacute;s a la campa&ntilde;a colorada, descart&oacute; por completo el v&iacute;nculo diplom&aacute;tico. </p>
                  <p>El Gobierno paraguayo no se ha cerrado a un posible establecimiento de relaciones con la Rep&uacute;blica Popular de China, seg&uacute;n indic&oacute; el propio presidente de la Rep&uacute;blica, Nicanor Duarte Frutos, al retornar al pa&iacute;s luego de una larga gira de catorce d&iacute;as. ”No descartamos ninguna posibilidad en el futuro; estamos en un mundo global, solamente exigiremos respeto, decencia y veracidad”, afirm&oacute;, aludiendo aparentemente a las versiones sobre el supuesto apoyo del gobierno taiwan&eacute;s a su campa&ntilde;a electoral. </p>
                  <p>El mandatario realiz&oacute; tales manifestaciones tras llegar al pa&iacute;s luego de una gira de dos semanas, que la inici&oacute; en la Rep&uacute;blica China de Taiw&aacute;n, pa&iacute;s con el cual Paraguay mantiene fuertes v&iacute;nculos basados principalmente en la exclusividad, habida cuenta del antagonismo entre ambas naciones asi&aacute;ticas. El viaje tambi&eacute;n incluy&oacute; Singapur y M&eacute;xico. </p>
                  <p>Las declaraciones del mandatario se contraponen a las del vicepresidente, Luis Castiglioni, quien hab&iacute;a cerrado puertas incluso al posible relacionamiento comercial, luego de que un funcionario de China Continental haya se&ntilde;alado que el gobierno de la isla hab&iacute;a solventado la campa&ntilde;a pol&iacute;tica que llev&oacute; a Duarte Frutos a la Presidencia de la Rep&uacute;blica.</p>
                  <p>&nbsp;</p>
                  <p><a href="#"><strong>arriba <img src="botones/flechaarriba.gif" width="9" height="8" border="0"></strong></a></p>
                  <p>&nbsp;</p>                  <p class="texto"><a name="Duarte" id="Duarte"></a></p>
                  <p><strong><strong><img src="botones/flecha.gif" width="8" height="9"> </strong></strong><strong>Duarte Frutos no descarta en el futuro relacionamiento con Pek&iacute;n </strong></p>                  
                  <p><strong></strong>Diario abc - Paraguay <strong>. <em>Ni bien retorn&oacute; ayer de Taiw&aacute;n, donde seg&uacute;n dijo obtuvo un cr&eacute;dito de US$ 30 millones, el Jefe de Estado no descart&oacute; ”ninguna posibilidad en el futuro”. Fue acerca del eventual relacionamiento con China continental. </em></strong></p>
                  <p><strong><em>”Solamente exigiremos respeto, decencia y veracidad”, dijo. Previamente habl&oacute; de un giro radical en el sistema de relacionamiento con Taiw&aacute;n” y de la reorientaci&oacute;n de nuestra pol&iacute;tica exterior </em></strong><strong>. </strong></p>
                  <p>”No descartamos ninguna posibilidad en el futuro. Estamos en un mundo global”, adujo Nicanor Duarte Frutos al ser requerido con respecto al posible relacionamiento con la Rep&uacute;blica Popular de China. A prop&oacute;sito, el gobernante brasile&ntilde;o Luiz Ignacio Lula Da Silva estuvo la semana anterior en Beijing, para hablar de la posible formalizaci&oacute;n de un acuerdo comercial entre China continental y el MERCOSUR. </p>
                  <p>&nbsp;</p>                  <p><a href="#"><strong>arriba <img src="botones/flechaarriba.gif" width="9" height="8" border="0"></strong></a></p>
                  <p>&nbsp;</p>                  <p class="texto"><a name="Consejo" id="Consejo"></a></p>
                  <p><strong><strong><img src="botones/flecha.gif" width="8" height="9"> </strong></strong><strong>XXVI Reuni&oacute;n del Consejo del Mercado Com&uacute;n </strong>                  </p>                  
                  <p><em><strong>RESUMEN DEL COMUNICADO CINJUNTO DE LOS PRESIDENTES DE LOS ESTADOS PARTES DEL MERCOSUR </strong></em></p>
                  <p>El pasado jueves 8 de julio se llev&oacute; a cabo la vigesimosexta Reuni&oacute;n del Consejo del Mercosur con la participaci&oacute;n de los Presidentes Nestor Kirchner (Argentina), Luiz Inacio Lula da Silva (Brasil), Nicanor Duarte Frutos (Paraguay) y Jorge Batlle Ib&aacute;&ntilde;ez (Uruguay). Los citados estadistas expresaron su satisfacci&oacute;n por la participaci&oacute;n de los presidentes de Bolivia, Carlos Meza, y de Chile, Ricardo Lagos, lo que confirma la voluntad del MERCOSUR de fortalecer lazos de asociaci&oacute;n con dichos pa&iacute;ses. Asimismo saludaron la presencia de los presidentes Hugo Ch&aacute;vez (Venezuela) y Vicente Fox (M&eacute;xico), al tiempo de destacar la presencia del vicepresidente colombiano, Francisco Santos Calder&oacute;n, y ministros de Per&uacute;, Jap&oacute;n, y Egipto. (1) </p>
                  <p>Se resalt&oacute; la creaci&oacute;n del Centro MERCOSUR de promoci&oacute;n del Estado de Derecho con sede en Asunci&oacute;n, al tiempo que los presidentes de los cuatro pa&iacute;ses miembros “ratificaron la importancia de garantizar la vigencia y la aplicaci&oacute;n de las normas MERCOSUR”, y “recibieron con satisfacci&oacute;n (...) el Anteproyecto de Protocolo Constitutivo del Parlamento del Mercosur”. <strong><em></em></strong>(2) </p>
                  <p>Los cuatro presidentes “resaltaron los &eacute;xitos de las actividades de promoci&oacute;n comercial conjunta desarrolladas por el MERCOSUR”, as&iacute; como por “la participaci&oacute;n conjunta en la Feria de Alimentos de SEUL 2004”, y por la “muestra institucional del Mercosur” en Berl&iacute;n. Pero de todos los logros de “promoci&oacute;n comercial conjunta” los cuatro miembros del Mercosur dieron un particular destaque a la III Misi&oacute;n Comercial del MERCOSUR a China que se realiz&oacute; en el marco de la visita del Presidente argentino a ese pa&iacute;s, declarando: “Esta misi&oacute;n (...) integrada por la m&aacute;s numerosa participaci&oacute;n empresarial en las misiones conjuntas del MERCOSUR hasta el presente, pone de manifiesto el gr&aacute;n inter&eacute;s del sector privado en esta iniciativa”. (3) </p>
                  <p>Los presidentes de Paraguay, Brasil, Argentina y Uruguay “reafirmaron su voluntad de profundizar las relaciones econ&oacute;micas y comerciales entre el MERCOSUR y la Rep&uacute;blica Popular de China. En ese sentido, se congratularon por la realizaci&oacute;n en Beijing del Quinto Di&aacute;logo entre ambas partes, en el que se conform&oacute; el Grupo de Enlace MERCOSUR-China y se acord&oacute; iniciar un estudio de factibilidad sobre un eventual acuerdo comercial.” (4) </p>
                  <p>Finalmente, los mandatarios de los pa&iacute;ses integrantes del MERCOSUR “manifestaron su compromiso con el &eacute;xito de la pr&oacute;xima Tercera Ronda de Negociaciones Comerciales, en el marco del 'Sistema Global de Preferencias Comerciales entre pa&iacute;ses en desarrollo' (SGPC) y se felicitaron por la invitaci&oacute;n realizada a los pa&iacute;ses miembros del Grupo de los 77 y China a participar en ella”. Manifestaron asimismo el deseo de que entre los participantes a dicha reuni&oacute;n se logren concesiones que redunden en una revitalizaci&oacute;n del comercio Sur-Sur (Mercosur, China y G-77), (5) </p>
                  <p>Firmando a continuaci&oacute;n, el comunicado conjunto, Nicanor Duarte Frutos, Nestor Kirchner, Luiz Inacio Lula da Silva y Jorge Batlle Iba&ntilde;ez. </p>
                  <p>&nbsp;</p>
                  <p align="center"><img src="images/fotos_nuevas/pag-24.gif" width="400" height="172"></p>
                  <p><strong>Citas textuales. </strong></p>
                  <p><strong>1. Comunicado conjunto de los Presidentes de los Estados Partes del Mercosur, p&aacute;g. 1, incisos 1 al 5. </strong></p>
                  <p><strong>2. Op.cit. p&aacute;g. 2, incisos 10, 11 y 13. </strong></p>
                  <p><strong>3. Op.cit. p&aacute;g. 4, inciso 20. </strong></p>
                  <p><strong>4. Op.cit. p&aacute;g. 7, inciso 43. </strong></p>
                  <strong>5. Op.cit. p&aacute;g. 8, inciso 50. </strong><p>&nbsp;</p>
                  <p><a href="#"><strong>arriba <img src="botones/flechaarriba.gif" width="9" height="8" border="0"></strong></a></p>
                  <p>&nbsp;</p>
                  <p class="texto"><a name="Creydt" id="Creydt"></a></p>
                  <p><strong><strong><img src="botones/flecha.gif" width="8" height="9"> </strong></strong><strong>Oscar Creydt y la “Presidencia de China”</strong>                  </p>                  
                  <p><strong><em></em></strong></p>
                  <p><strong><em>INTERESANTE VISION “PROFETICA” DE UN GRAN INTELECTUAL Y REVOLUCIONARIO PARAGUAYO</em></strong></p>
                  <p><em>En marzo de 1987 fallec&iacute;a quien fuera uno de los pensadores m&aacute;s discutidos de la pol&iacute;tica paraguaya, Oscar Creydt. </em></p>
                  <p><em>Su figura y sus ideas, brillantes, francas, libres, rebeldes y radicalmente patri&oacute;ticas, fueron siempre discriminadas por su intensa militancia comunista, detalle que era y a&uacute;n es- grave pecado en la generalidad intelectual del Paraguay. </em></p>
                  <p><em>Pero m&aacute;s all&aacute; de los prejuicios y diferencias ideol&oacute;gicas que se puedan tener contra &eacute;l, Creydt era un hombre culto y cosmopolita, que conoci&oacute; profundamente al Paraguay y que recorri&oacute; el mundo buscando aprehender, en las victorias y fracasos de otras naciones, las f&oacute;rmulas para el progreso y el desarrollo de sus compatriotas. </em></p>
                  <p><em>La gentileza del prologuista, el excelente periodista Antonio Carmona, quien nos acercara la edici&oacute;n de la obra que citamos, nos permit&iacute;o elaborar este material.</em></p>
                  <p><img src="images/fotos_nuevas/pag-27.gif" width="240" height="328" align="right">Si bien Creydt era un cr&iacute;tico de la realidad paraguaya y en eso todos los paraguayos coincidimos desde hace cuatro siglos, se diferenciaba de la mayor&iacute;a de nuestros compatriotas en cuatro cosas: 1). Buscaba, estudiaba y aportaba soluciones concretas para nuestro pa&iacute;s; 2). No se resignaba a aceptar una <em>realidad fatalista </em> del pa&iacute;s; 3). No se dejaba influenciar f&aacute;cilmente por ideas ajenas pensaba por si mismo-; y 4). Era un hombre que aceptaba sus errores, cambiaba y evolucionaba permanentemente. Dicho en otras palabras, su filosof&iacute;a personal era “la b&uacute;squeda”. </p>
                  <p>Habiendo nacido en 1906 y tras tener una buena educaci&oacute;n- parte en Alemania y parte en su Paraguay natal-, siempre fue revolucionario y rebelde, en una &eacute;poca en la cual, serlo era <em>pr&aacute;cticamente suicida </em>. Su pensamiento, que &eacute;l mismo defini&oacute; como <em>comunista, </em> tiene en realidad ra&iacute;ces profundamente humanistas, y toda su lucha intelectual ten&iacute;a como claro objetivo la b&uacute;squeda del bienestar, progreso y desarrollo de la naci&oacute;n paraguaya. </p>
                  <p>Creydt parte de un an&aacute;lisis hist&oacute;rico de los mismos or&iacute;genes de la patria, y observa, horrorizado, c&oacute;mo nuestros ancestros primero los guaran&iacute;es y m&aacute;s tarde los criollos independientes, fueron sucesivamente oprimidos por los conquistadores espa&ntilde;oles: “Como resultado del ba&ntilde;o de sangre de 1545, la organizaci&oacute;n tribal de los guaran&iacute;es vecinos de Asunci&oacute;n fue destruida. (...) Veinte mil indios, el resto de la gran tribu- fueron repartidos entre trescientos colonizadores en forma desigual.” (1) </p>
                  <p>Creydt descubre que el avasallamiento y la explotaci&oacute;n han sido una suerte de <em>comun denominador </em> en </p>
                  <p>la formaci&oacute;n del Paraguay, pa&iacute;s que desde su mismo or&iacute;gen “se form&oacute; como un conjunto numeroso y extendido de villas y pueblos esencialmente agr&iacute;colas”. Advierte que su patria es una naci&oacute;n absolutamente peculiar y diferente de sus vecinos, en muchos aspectos m&aacute;s independiente que otras naciones del Conosur, y que dicha “formaci&oacute;n particular se deb&iacute;a a que la econom&iacute;a del Paraguay, precisamente por ser menos desarrollada, era menos dependiente de Espa&ntilde;a, (...) que las dem&aacute;s colonias.” (2). En sus mismos or&iacute;genes, la planificaci&oacute;n del Paraguay fue diferente a la que tuvieron, por ejemplo, las dem&aacute;s colonias espa&ntilde;olas y portuguesas, ya que “ mientras que en las provincias del R&iacute;o de la Plata se conced&iacute;a tierra solamente a hombres ricos que compraban grandes latifundios, en el Paraguay los gobernadores, libres del control central, pod&iacute;an conceder tierras a gente de pocos recursos” (3) . </p>
                  <p>Pese a la independencia paraguaya, y pese a las dos guerras que asolaron a nuestro pa&iacute;s, y aun mucho despu&eacute;s de la revoluci&oacute;n del 47, Creydt segu&iacute;a viendo a nuesto pa&iacute;s sojuzgado, avasallado y oprimido, como hab&iacute;a estado bajo la “Encomienda” espa&ntilde;ola o en las Reducciones Jesu&iacute;ticas. En 1963, Creydt escrib&iacute;a: “El pueblo est&aacute; cansado de palabras. El pueblo est&aacute; harto de promesas vanas y de planes (...) que no se cumplen nunca. El pueblo quiere hechos. Si queremos demostrar al pueblo que algo ha cambiado en el pa&iacute;s (...) el gobierno debe apresurarse a tomar medidas eficaces para aliviar la pavorosa situaci&oacute;n de miseria a que la dictadura ha condenado a las masas”. </p>
                  <p>Quiz&aacute;s haya sido la visi&oacute;n de tanta y tan larga opresi&oacute;n del pueblo paraguayo, lo que llev&oacute; a Creydt a buscar una salida en el comunismo, y con ese motivo comenz&oacute; a viajar y a observar la realidad que se presentaba en los principales pa&iacute;ses comunistas del mundo. Entusiasmado con los libros de Lenin lleg&oacute; a Cuba donde sufri&oacute; una gran decepci&oacute;n porque “la pol&iacute;tica no era manejada ni por el partido ni por los campesinos, sino por la polic&iacute;a cubana”. Tras su gran chasco en La Habana, no dud&oacute; en efectuar dur&iacute;simas cr&iacute;ticas al r&eacute;gimen de Castro, declar&aacute;ndose pro-sovi&eacute;tico. Pero m&aacute;s tarde, al descubrir que la U.R.S.S. intentaba ejercer una suerte de control y mandato sobre el Partido Comunista Paraguayo, se enfrent&oacute; abiertamente a las m&aacute;s altas autoridades del gobierno ruso, causando el malestar de varios “comunistas” paraguayos cuyo verdadero inter&eacute;s estaba en los d&oacute;lares que Mosc&uacute; peri&oacute;dicamente les enviaba para sus “gastos”. </p>
                  <p>Fue entonces que, nuevamente decepcionado, viaj&oacute; a Vietnam, donde pudo mezclarse entre el pueblo en plena guerra contra EE.UU. y observar sorprendido c&oacute;mo maestros y agricultores defend&iacute;an al pa&iacute;s contra la armada m&aacute;s poderosa del planeta. Pudo tomar el t&eacute; y dialogar personalmente con el propio Ho Chi Min, personalidad sencilla que cambi&oacute; para siempre el pensamiento de Creydt, quien reci&eacute;n entonces comenz&oacute; a descubrir aquello que tanto tiempo hab&iacute;a buscado. El Paraguay no necesitaba ser aliado de Rusia ni de Estados Unidos, la soluci&oacute;n no pasaba por all&iacute;, seg&uacute;n lo que aprendi&oacute; de las propias palabras del l&iacute;der vietnamita. Lo que Paraguay necesitaba era “una revoluci&oacute;n de liberaci&oacute;n nacional, con la consigna del doctor Francia de <em>no mudar de amo </em>”. (4) Ho Chi Min le dijo a Creydt que Vietnam confiaba solo en su propia fuerza, en su propio pueblo, “El factor principal de la derrota del imperialismo norteamericano en Vietnam fue naturalmente la lucha tenaz, sacrificada, de la naci&oacute;n vietnamita”. </p>                  
                  <p>Pero Oscar Creydt descubri&oacute; que hab&iacute;a un segundo factor que apuntalaba el &eacute;xito vietnamita: “El segundo factor fue la presencia de China, que impidi&oacute; al Pent&aacute;gono destruir lo que este llamaba “el santuario”, o sea, Vietnam del Norte” (5). Hasta ese momento, en parte por prejuicios personales pero mayormente por influencia de la propaganda sovi&eacute;tica, Creydt se hab&iacute;a mostrado abiertamente contrario a China. Pero fue invitado por Ho Chi Min a visitar ese pa&iacute;s y dialogar con sus autoridades. Pese a los en&eacute;rgicos discursos que, anteriormente, Creydt hab&iacute;a hecho contra Mao Tse Tung, pudo visitar sin problemas la gran naci&oacute;n asi&aacute;tica, donde fue recibido con cierta desconfianza, pero pese a todo ello, el viajero paraguayo sali&oacute; “gratamente impresionado de ese pa&iacute;s”. En China Creydt descubri&oacute; que el modelo de desarrollo econ&oacute;mico con base en la producci&oacute;n campesina <em>ten&iacute;a un gran futuro </em>, y vi&oacute; all&iacute; grandes perspectivas de crecimiento y progreso que, estaban totalmente ausentes en el sistema sovi&eacute;tico. </p>
                  <p>A su regreso de China, las autoridades rusas intentaron retenerlo definitivamente en el pa&iacute;s, por temor a que Creydt pudiera transmitir a sus compatriotas paraguayos <em>las ideas chinas. </em> “Yo estaba secuestrado en la Uni&oacute;n Sovi&eacute;tica, estuve secuestrado desde mi regreso del Vietnam hasta mi salida, esto es un hecho”. “Hab&iacute;a un plan para internarme en una cl&iacute;nica para locos, que es el m&eacute;todo ruso de inutilizar opositores” (6) . </p>
                  <p>Creydt se dio cuenta claramente de que hab&iacute;a una profunda diferencia en la forma de proceder entre las grandes potencias. China no interfer&iacute;a en los asuntos internos de otros pueblos, ofrec&iacute;a su ayuda en casos de emergencia, pero eran estos mismos pueblos quienes deb&iacute;an lograr su independencia y desarrollo. En cambio las otras potencias interven&iacute;an directamente en el quehacer interno de los pueblos, infiltrando sus agentes y sobornando gobiernos. No tuvo ning&uacute;n temor en decirle a los rusos que lo ten&iacute;an pr&aacute;cticamente secuestrado en Mosc&uacute;, que “el pueblo paraguayo es un pueblo peque&ntilde;o, por tanto puede ser ofendido f&aacute;cilmente, pero en cualquier situaci&oacute;n el pueblo paraguayo conserva su dignidad”. (7) </p>
                  <p>En cambio, el gobierno chino ofrec&iacute;a un franco apoyo al <em>pueblo </em> y gobierno paraguayos, para el logro de su independencia y desarrollo, sin entrometerse ni en sus asuntos internos ni en su ideolog&iacute;a, y sin tener intereses de “conquistar” o infiltrarse en nuestra naci&oacute;n. El propio Creydt vi&oacute;, hace 35 a&ntilde;os, que la propuesta china era m&aacute;s franca y m&aacute;s respetuosa, pese a que &eacute;l profesaba puntos de vista diferentes al gobierno de Mao: al respecto manifest&oacute; francamente: “Tengo divergencias con los chinos, yo no soy pro-chino” (8) , pero descubri&oacute; que una relaci&oacute;n bilateral paraguayo-china era la &uacute;nica salida real y concreta para el desarrollo de nuestro pa&iacute;s. Y esa idea se fue afirmando cada vez m&aacute;s hasta su muerte, en 1987. </p>
                  <p>Hoy d&iacute;a, a la luz de la historia reciente, el brillante pensamiento del temperamental escritor y activista pol&iacute;tico paraguayo se torna cada vez m&aacute;s certero y <em>prof&eacute;tico </em>: la URSS se derrumb&oacute; sobre s&iacute; misma hace casi veinte a&ntilde;os y las <em>grandes potencias occidentales </em>incluyendo Rusia, se tambalean entre la crisis econ&oacute;mica y un repugnante repunte del terrorismo internacional. </p>
                  <p>Paraguay tiene hoy m&aacute;s que nunca la oportunidad de marcar su propio derrotero hacia el futuro. La pr&oacute;spera China ha tendido un puente de progreso, amistad y libre comercio hacia el Mercosur. Nuestros socios del Mercosur ya est&aacute;n transitando esa senda, y si el Paraguay contin&uacute;a demorando dicha integraci&oacute;n, lo &uacute;nico que lograremos es aumentar nuestra ya rezagada posici&oacute;n. </p>
                  <p>1. “Formaci&oacute;n hist&oacute;rica de la naci&oacute;n paraguaya”. Oscar Creydt. P&aacute;g. 48. </p>
                  <p>2. Op.Cit. P&aacute;g. 64. </p>
                  <p>3. Op.Cit. P&aacute;g. 63. </p>
                  <p>4. Op.Cit. P&aacute;g. 332. </p>
                  <p>5. Op.Cit P&aacute;g. 328. </p>
                  <p>6. Op.Cit P&aacute;g. 254. </p>
                  <p>7. Op.Cit P&aacute;g. 252. </p>
                  <p>8. Op.Cit P&aacute;g. 329. </p>                  <p>&nbsp;                  </p>
                  <p><a href="#"><strong>arriba <img src="botones/flechaarriba.gif" width="9" height="8" border="0"></strong></a></p></td>
              </tr>
              <tr>
                <td valign="top" class="texto">&nbsp;</td>
              </tr>
            </table></td>
          </tr>
          <tr>
            <td background="images/fondito-secciones.jpg"><img src="images/ultima-barra-secciones.jpg" width="585" height="43"></td>
          </tr>
        </table></td>
      </tr>
      <tr>
        <td colspan="2" valign="top" background="images/fondo-noticias.jpg"><img src="images/barra-abajo.gif" width="780" height="8"></td>
        </tr>
    </table></td>
  </tr>
  <tr>
    <td height="30" align="center" bgcolor="#FFFFFF" class="texto_menu"><a href="index.php">Home</a> | <a href="conozcanos.php">Con&oacute;zcanos</a> | <a href="cultura.php">Cultura </a> | <a href="historia.php">Historia</a> | <a href="politica.php">Pol&iacute;tica</a> | <a href="economia.php">Econom&iacute;a</a> | <a href="noticias.php">Noticias</a><a href="noticias.php"></a> | <a href="relaciones.php">Relaciones con el Paraguay</a> | <a href="contactenos.php">Cont&aacute;ctenos</a> </td>
  </tr>
  <tr>
    <td align="center" bgcolor="#F3F3F3" class="texto_menu"><p><strong>Sitio Web:</strong> <a href="http://www.apachin.org"><strong>www.apachin.org</strong></a>; <strong>E-mail:</strong> <a href="mailto:presidencia@apachin.org"><strong>presidencia@apachin.org</strong></a><br>
        <strong>Establecido en:</strong> Edificio L&iacute;der IV piso 13 of. 131 - <strong>Telefax.:</strong> (595.21. 498 780)<br>
      Copyright (c) 2004. APACHI.<br>
Todos los derechos reservados.</p>
    <p>Dise&ntilde;o &amp; Hosting by <a href=http://www.apunto-web.com>Apunto-Web.com </a></p></td>
  </tr>
</table>
</body>
</html>
